#FROM node:alpine
FROM docker.repository.esi.adp.com/clientcentral/node:12.7.0
WORKDIR /app
COPY package.json .
#RUN npm i
#RUN npm install
COPY . .
CMD ["npm", "start"]

EXPOSE 3000

# FROM node:16

# WORKDIR /usr/src/app
# COPY package*.json ./

# RUN npm install

# COPY . .

# EXPOSE 8005

# CMD [ "node", "index.js" ]