pipeline {
  agent any
  stages {
    stage('Install Packages') {
      steps {
        bat 'npm install'
        bat 'npm upgrade'
        bat 'npm install chart.js'
      }
    } 
        stage('Create Build Artifacts') {
          steps {
            bat 'npm run build'
          }
        }
    //replace order-ui with your docker image name at all places    
    stage('Docker Build') {
            steps {
            echo 'Docker Build'
        bat 'docker build -t  docker.repository.esi.adp.com/clientcentral/training:s2-b1-t4-ems-frontend-img -f Dockerfile .'
            //bat label: 'Docker Build', script: '''docker build -t docker.repository.esi.adp.com/clientcentral/training:order-ui -f Dockerfile .'''
            }
        }
    
    stage('Docker Push'){
            steps {
                bat 'docker push docker.repository.esi.adp.com/clientcentral/training:s2-b1-t4-ems-frontend-img'
            }
        }
        
        stage('Docker deploy'){
            steps {
               
                bat 'docker run -itd -p  3000:3000 docker.repository.esi.adp.com/clientcentral/training:s2-b1-t4-ems-frontend-img'
            }
        }
  }
  }
